% rebase('layout.tpl', title=title, year=year)
<div class="jumbotron">
<font face="monotype corsiva" color="maroon"><u>
<h1><center>Padma Subrahmanyam</h1></u></font></center>
<hr color="maroon" size=5><font size=4 align="justify">
<p>
<p>Born to late K. Subrahmanyam and Meenakshi, Padma Subrahmanyam (Director, Nrityodaya, Chennai, India) is acclaimed as a rare combination of a dancer, research scholar, choreographer, music composer, singer, teacher, author, Indologist and one of the most outstanding artistes of today. Her father Director K. Subrahmanyam was an internationally reputed film pioneer, freedom fighter and a parental personality in the cultural field. Her mother Meenakshi was a music composer, a lyricist in Sanskrit and Tamil and an instrumentalist who played the veena, violin and harmonium.
<p>Encouraged by her father, Padma Subrahmanyam started learning under Kausalya who was a young teacher at Nrityodaya, the dance school founded by her father in 1942. Later, she came under the wings of guru Vazhuvoor Ramaiah Pillai and had her arangetram in 1956. From Dandayuthapani Pillai, she learnt adavus, from Gowri Ammal she learnt abhinaya. From various devadasis, she learnt 150 different adavus. Thus began her research.
She gave performances conducted by her guru, her school and also continued her college education. Padma has a Bachelor’s degree in Music, Master’s in Ethno Musicology and Ph.D in dance. Her music training was under the famous B.V. Lakshman and Salil Chaudhry.
<br><br>
<p>Padma scores the music for most of her productions apart from numerous individual compositions. For a couple of dance dramas for the Singapore Government she has used a multinational orchestra for her music. Thirty-five years ago, she was the first dancer to introduce Pushpanjali as a dance piece. She was the first dancer to use a “meera bhajan” to be scored to suit the grammar of “Pada Varnam”.
Having a flair for singing in various Indian and foreign languages from childhood, she has accompanied her sister – in - law Shyamala Balakrishnan, who was a highly reputed singer and research scholar in classical and folk music. They have both sung for a couple of albums titled “Folk music of Tamilnadu” and “Deiva Tamizh Isai”. Padma has also sung “Jayadeva’s Ashtapadis” for a separate album. She sings now for several dance performances of her disciples accompanied by Gayatri Kannan, her nephew’s wife.
<br><br>
<p>Her creativity as dancer and choreographer includes expansion of the technique through the use of the entire body with leaps and extension of legs and fast footwork for ramification of rhythm. Padma has revived mono-acting technique (Banika style) through Krishnaya Tubhyam Namaha, Ramaya Tubhyam Namaha, Jaya Jaya Sankara and other productions. She has given several solo and group presentations (including dance dramas) such as Meenakshi Kalyanam, Viralimalai Kuravanji, Valli Kalyanam, Silappadikaram, Krishna Tulabaram, Parijata Aharanam, Nagarukku Appal, Geetanjali, Shyama, Sri Gurave Namaha, Pavai Nombu, Vande Mataram (specially produced for the Golden Jubilee of India's Independence) and so on.
<br><br><center><img src="/static/images/ps1.jpg" height=200 width=200><br><br></center><br>
<p>When helping her brother Balakrishnan research for a documentary on temples, she stumbled upon the karanas - dance sculptures illustrating the Natya Sastra texts. She also read books by Ananda Coomaraswamy, T. N. Ramachandran and C. Sivaramamurthy. This heralded her research into the world of dance sculpture and she eventually did her thesis on ‘Karanas in Indian dance and sculpture’ as seen in the temples of Chidambaram, Thanjavur and Kumbakonam, for her Ph.D from Annamalai University. As a research scholar she has helped highlight the fact that the 108 Karanas (basic units of dance) are actually movements and not just static poses. She proved that dance sculptures are like photographs of moving dancers. She reconstructed these movements in their entirety through a correlated study of literature, sculptures and inscriptions, coupled with her own experiences as a dancer. Being an Indologist and a Sanskrit scholar, T. N. Ramachandran helped her greatly but Padma had years of devoted and painstaking research to do from a dancer's viewpoint, which resulted in 2 big volumes. Her research has established the unity of all Indian dances under the umbrella of the Natya Sastra and she conducts many workshops and camps on the subject.
<br><br>
<p>Post independent India has seen the revival of various regional dance forms such as Bharatanatyam, Odissi, Kathak, Manipuri, Kathakali, Kuchipudi etc. Padma is the first to discover the long forgotten grammatical artistic base in ‘Marga’ i.e. the path shown by sage Bharatha, common to all Indian forms. Like how the Sanskrit language co-existed with all the regional languages, the ‘Marga’ had co-existed with the indigenous groups till about 5 centuries ago. Padma has revived this Marga technique common to the entire Indian subcontinent and even beyond. Based on her research, she announces her programs as ‘Bharatha Nrityam’. Also, using the same communication technique and using the language of the respective regions, she has choreographed Bharatha Nrityam recitals in Tamil, Kashmiri, Hindi, Bengali, Oriya, Marathi, Kannada, Telugu and Malayalam languages. She has also used Russian songs to demonstrate the ‘abhinaya’ technique.
Even as a teenager, Padma started teaching at Nrityodaya. She is now the Director of this institution. At Nrityodaya, the syllabus also includes Sanskrit and Indology. Deserving poor students are given free training. She has trained many dancers / teachers as well as musicians for accompanying dance including nattuvangam artistes.
<br><br>
<p>She has designed the sculptures of the 108 Karanas of Lord Siva and Godess Parvati in black granite for the Nataraja temple at Satara in Maharashtra, an undertaking she took on at Kanchi Paramacharya's bidding. She was asked to freeze those movements of the Karanas, which are not sculpted in the older temples of Tanjore or Chidambaram. She has made use of the twin figures of Siva and Parvati to bring out the animation of each of the Karana movements.
Twelve years after completing her design of these 108 Karana figures, she discovered by the grace of the sage of Kanchi, about 50 Karana sculptures in the world-renowned monument temple complex at Prambanan in Central Java, Indonesia belonging to the 9th century AD. The remarkable historic feature of these figures is that they totally tally with her own designs for the temple at Satara. This ‘link beyond time and space’ is the subject of a book by an Italian archaeologist Dr.Alessandra who did her post - doctoral research under Padma through the British Academy, London. Immersed in the Natya Sastra and each new finding related to it, like in the 9th century bas reliefs in Prambanan where the Karanas are identical to her own interpretations in Satara, gives her a sense of great fulfillment.
<br><br>
<p>She has numerous articles, research papers and travelogues to her credit like “Bharata’s Art – then and now”, “Bharatakkalai Kotpadu” (in Tamil), “Natya Sastra and National Unity” and “Kanchi Mahaswami’s Vision of Asian Culture”. She has written ‘Legacy of a Legend’ which is a collection of articles by her. Her latest books are “Valluvarum Vedaneriyum” (in Tamil) and “Bhagavad Gita for Dance”. She wrote the script, scored music, choreographed and personally appeared in the 13-segment film “Bharatiya Natya Sastra” produced by Nrityodaya and directed by her brother V Balakrishnan which was telecast on Doordarshan National network. This film won her the “Panchajanyam Award” from Vigil, a public opinion forum. Russia has produced a film on Padma titled “Queen of Dance”. NHK, Japan has made a film on her under their series “Asia’s Who’s Who”. Another film “Padma” was produced by Film Australia. Films Division, Govt of India has also produced a film on her. Padma’s life and contribution is the subject of a dissertation for a Master’s degree in Sociology written by Chamundeswari. Her biography in Tamil has been done by Padma’s disciple Sundari Santhanam. In November 2001, Padma has presented a video production “Natya Sastramum Nadigar Tilagamum” with a compilation of clippings from about 50 films of the legendary actor Sivaji Ganesan, to prove that self-experience in the field of theater leads to adhering to theoretical rules laid down in the Natya Sastra, even if there is no knowledge of the text.
<br><br>
<p>Padma Subrahmanyam is the recipient of many awards including Padmashri, Sangeet Natak Akademi Award, Kalaimamani Award from Govt of Tamilnadu, Kalidas Samman from Govt of Madhya Pradesh, Bharata Sastra Rakshamani from His Holiness Jagadguru Sankaracharya of Kanchi Kamakoti Peetam, Nada Brahmam from Narada Gana Sabha in Chennai, Soviet Land Nehru Award, Isai Perarignar from Tamil Isai Sangam in Chennai, Chowdiah Award from Academy of Fine Arts in Bangalore, Thirumurai Nadana Perarisi from Sekkizhar Manram, Satabdi Narthaki at a felicitation in Mumbai, Pragna Puraskar and the latest being Kambarasa Nartana Vilasa Vittagi from Colombo Kamban Kazhagam.
She has also received the prestigious “Fukuoka Asian Cultural Prize” from Japan for her contribution to development and harmony in Asia. She has also been a member of the General Council of Indian Council for Cultural Relations, the Executive Committee of the Sangeet Natak Akademi, New Delhi and the Tamilnadu Iyal Isai Nataka Manram, Chennai. She has been associated with many universities and is also a member of the Advisory Committee for Chennai Doordarshan.
<br><br>
<p>With total support from her family members who have pooled in with their collective talents, Padma has established herself as a dancer and researcher. Her easy to understand gestures, explicit facial expressions, impeccable timing, pirouetting movements and original ideas have held her audiences riveted over the years.

</p>
</center>
<hr color="maroon" size=6>
</font>
</div>