% rebase('layout.tpl', title=title, year=year)
<div class="jumbotron">
<font face="monotype corsiva" color="maroon" align="justify"><u>
<h1><center>Red Fort</h1></u></font></center>
<hr color="maroon" size=5><font size=4>
<p>
The Red Fort is a historic fort in the city of Delhi in India that served as the main residence of the Mughal Emperors.Named for its massive enclosing walls of red sandstone, it is adjacent to an older fort, the Salimgarh, built by Islam Shah Suri in 1546, with which it forms the Red Fort Complex. The private apartments consist of a row of pavilions connected by a continuous water channel, known as the Nahr-i-Behisht. The Red Fort is considered to represent the zenith of Mughal creativity which, under the Shah Jahan, was brought to a new level of refinement. The planning of the palace is based on Islamic prototypes, but each pavilion reveals architectural elements typical of Mughal building, reflecting a fusion of Persian, Timurid and Hindu traditions The Red Fort’s innovative planning and architectural style, including the garden design, strongly influenced later buildings and gardens in Rajasthan, Delhi, Agra and further afield.</p>
<p>The fort’s massive red sandstone walls, which stand 75 feet (23 metres) high, enclose a complex of palaces and entertainment halls, projecting balconies, baths and indoor canals, and geometrical gardens, as well as an ornate mosque. Among the most famous structures of the complex are the Hall of Public Audience (Diwan-i-Am), which has 60 red sandstone pillars supporting a flat roof, and the Hall of Private Audience, which is smaller, with a pavilion of white marble.</p>
<p>‘At the stroke of the midnight hour, when the world sleeps, India will awake to life and freedom…’ This historic speech marked India’s independence from British rule and simultaneously made the Red Fort in Delhi a politically significant monument, which now acts as the setting for the independence day celebrations each year. However, the Red Fort has been a strategically important monument through the ages, due to Delhi being the capital city for a good part of the Mughal rule in India.</p>
<center><center><img src="/static/images/redfort1.jpg" height=400 width=400></center>
<p>Delhi's famous Red Fort is known by that name because of the red stone with which it is built and it is one of the most magnificent palaces in the world. India's history is also closely linked with this fort. It was from here that the British deposed the last Mughal ruler, Bhadur Shah Zafar, marking the end of the three century long Mughal rule. It was also from its ramparts that the first Prime Minister of India, Pandit Jawharlal Nehru, announced to the nation that India was free form colonial rule.

The Mughal emperor, Shah Jahan, after ruling from Agra for eleven years, decided to shift to Delhi and laid the foundation stone of the Red Fort in 1618. For its inauguration in 1647, the main halls of the palace were draped in rich tapestry and covered with silk from china and velvet from Turkey. With a circumference of almost one and a half miles, the fort is an irregular octagon and has two entrances, the Lahore and Delhi Gates.
Form the Lahore Gate, a visitor has access to the Chatta Chowk (vaulted arcade) which as once a royal market and housed court jewellers, miniature painters carpet manufacturers, workers in enamel, silk weavers and families of specialized craftsmen. The road from the royal market leads to the Nawabarkhana (band house) where the royal band played five times a day. The band house also marks the entry into the main palace and all visitors, except royalty had to dismount here.
The Diwan-e-Aam is the Red Fort's hall of public audience. Built of sandstone covered with shell plaster polished to look like ivory, the 80 x 40 feet hall is sub-divided by columns. The Mughal emperors would hold court here and meet dignitaries and foreign emissaries. The most imposing feature of the Diwan-e-Aam is the alcove in the back wall where the emperor sat in state on a richly carved and inlaid marble platform. In the recess behind the platform are fine examples of Italian pietra-dura work.
The piece de resistance of the fort, the Diwan-e-Khas was the hall of private audience. The most highly ornamented of all Shah Jahan's buildings, the 90 x 67 feet Diwan-e-Khas is a pavilion of white marble supported by intricately carved pillars. So enamoured was the emperor by the beauty of this pavilion that he engraved on it the following words: "If there is paradise on the face of this earth, it is this, it is this."
Richly decorated with flowers of inlaid mosaic work of cornelian and other stones, the Diwan-e-Khas once housed the famous Peacock Throne, which when it was plundered by Nadir Shah in 1739, was valued at six million sterling.</p>

</p>
</center>
<hr color="maroon" size=6>
</font>
</div>