% rebase('layout.tpl', title=title, year=year)
<div class="jumbotron">
<font size=5 color="maroon"
<u><h1><center>SUDHA RAGUNATHAN</h1></center></u></font>
<hr color="maroon" size=5><font size=4 align="justify">
<p>One of the brightest stars of Carnatic music in India, her distinctly stunning vocal style has ignited musical imagination and spirit across languages, frontiers and ideologies. Explore this website to know more about this diamond in the sky.<br>
Sudha’s foray into the world of music began with her mother, Smt. Choodamani, who initially trained her, and then put her under the tutelage of Vidwan Sri B.V Lakshman. As a child, Sudha participated in several music competitions and was immersed in carnatic music, but she also excelled academically. As an intelligent and talented individual, it is no surprise that Sudha won the ‘Outstanding Student’ award at Ethiraj College (for all the three years during her graduation) while simultaneously increasing her musical repertoire by leaps and bounds. In 1977, Sudha received a scholarship from the Central Government that gave her the opportunity to study under Padmabhushan Sangita Kalanidhi Dr. M.L. Vasanthakumari, known by many as a musical genius and a doyenne of carnatic music. This would mark the beginning of her musical ascendency and her journey to becoming MLV’s vaarisu. During this time, Sudha was given the golden chance to provide vocal support to MLV (as she was affectionately called) for over a decade. When asked about her Guru, Sudha often says, “Music was only one of the few things she taught me. She taught me how to live life to its fullest.” Sudha vividly recalls how while singing with her Guru, a sangathi in Yaman Kalyani would get woven into an Ashtapathi in Ragamalika. Spontaneously, MLV would stop singing and allow Sudha to take over. She fondly remembers her Guru as a generous soul, both onstage and off.
<br><br>
<br><center><img src="/static/images/suda1.jpg" height=300 width=300><br><br></center>
<p><br>Sudha’s foray into the world of music began with her mother, Smt. Choodamani, who initially trained her, and then put her under the tutelage of Vidwan Sri B.V Lakshman. As a child, Sudha participated in several music competitions and was immersed in carnatic music, but she also excelled academically. As an intelligent and talented individual, it is no surprise that Sudha won the ‘Outstanding Student’ award at Ethiraj College (for all the three years during her graduation) while simultaneously increasing her musical repertoire by leaps and bounds. In 1977, Sudha received a scholarship from the Central Government that gave her the opportunity to study under Padmabhushan Sangita Kalanidhi Dr. M.L. Vasanthakumari, known by many as a musical genius and a doyenne of carnatic music. This would mark the beginning of her musical ascendency and her journey to becoming MLV’s vaarisu. During this time, Sudha was given the golden chance to provide vocal support to MLV (as she was affectionately called) for over a decade. When asked about her Guru, Sudha often says, “Music was only one of the few things she taught me.
She taught me how to live life to its fullest.” Sudha vividly recalls how while singing with her Guru, a sangathi in Yaman Kalyani would get woven into an Ashtapathi in Ragamalika. Spontaneously, MLV would stop singing and allow Sudha to take over. She fondly remembers her Guru as a generous soul, both onstage and off.<br><p>
</div>